"""Initial migration

Revision ID: 2df915a8c6ec
Revises: 
Create Date: 2025-10-24 12:00:21.081787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2df915a8c6ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('challenger_id', sa.String(length=255), nullable=False),
    sa.Column('challengee_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('challenger_finished', sa.Boolean(), nullable=True),
    sa.Column('challengee_finished', sa.Boolean(), nullable=True),
    sa.Column('challenger_points', sa.Integer(), nullable=True),
    sa.Column('challengee_points', sa.Integer(), nullable=True),
    sa.Column('versuslist', sa.ARRAY(sa.Integer(), dimensions=1), nullable=True),
    sa.Column('challenger_bool', sa.ARRAY(sa.Boolean(), dimensions=1), nullable=True),
    sa.Column('challengee_bool', sa.ARRAY(sa.Boolean(), dimensions=1), nullable=True),
    sa.Column('challenger_pic_points', sa.ARRAY(sa.Integer(), dimensions=1), nullable=True),
    sa.Column('challengee_pic_points', sa.ARRAY(sa.Integer(), dimensions=1), nullable=True),
    sa.Column('playger_button_status', sa.Boolean(), nullable=True),
    sa.Column('playgee_button_status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.String(length=255), nullable=True),
    sa.Column('challenger_score', sa.Integer(), nullable=False),
    sa.Column('challengee_score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pictures',
    sa.Column('pictureid', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('coordinates', sa.ARRAY(sa.Float(), dimensions=1), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('place', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('pictureid')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('usersdaily',
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('played', sa.Boolean(), nullable=True),
    sa.Column('last_played', sa.Date(), nullable=True),
    sa.Column('last_versus', sa.Date(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usersdaily')
    op.drop_table('users')
    op.drop_table('pictures')
    op.drop_table('matches')
    op.drop_table('challenges')
    # ### end Alembic commands ###
