"""Initial migration

Revision ID: 4cf15f9fdaf9
Revises: 
Create Date: 2025-10-24 11:27:52.357294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cf15f9fdaf9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenges', 'challenger_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('challenges', 'challengee_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('challenges', 'status',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('matches', 'challenge_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('matches', 'challenger_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('matches', 'challengee_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pictures', 'pictureid',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.alter_column('pictures', 'coordinates',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               nullable=False)
    op.alter_column('pictures', 'link',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('pictures', 'place',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('usersdaily', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usersdaily', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('pictures', 'place',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('pictures', 'link',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('pictures', 'coordinates',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               nullable=True)
    op.alter_column('pictures', 'pictureid',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    op.alter_column('matches', 'challengee_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('matches', 'challenger_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('matches', 'challenge_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('challenges', 'status',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('challenges', 'challengee_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('challenges', 'challenger_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
