"""add name and year to users table

Revision ID: 74e63e0c8e89
Revises: 2df915a8c6ec
Create Date: 2025-10-27 20:46:29.628712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74e63e0c8e89'
down_revision: Union[str, None] = '2df915a8c6ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('year', sa.String(length=255), nullable=True))
    op.add_column('usersdaily', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('usersdaily', sa.Column('year', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usersdaily', 'year')
    op.drop_column('usersdaily', 'display_name')
    op.drop_column('users', 'year')
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###
